php artisan migrate:make create_rbac_user_table 
php artisan migrate:make create_rbac_menu_table 
php artisan migrate:make create_rbac_module_table 
php artisan migrate:make create_rbac_button_table 
php artisan migrate:make create_rbac_role_table 
php artisan migrate:make create_pub_log_table 
php artisan migrate:make create_pub_sequence_table 
php artisan migrate:make create_pub_person_table 
php artisan migrate:make create_pub_organize_table 